sigma_final/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Redirect::to('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/maquinarias/list', 'MaquinariasController@data');

Route::resource('maquinarias', 'MaquinariasController');
Route::resource('maquinarias.mpreventivos', 'MpreventivosController' );

Route::get('/ubicacion/provincia/{id}', 'UbicacionController@maquinarias');
Route::get('/ubicacion/maquinaria/{serie}', 'UbicacionController@buscarMaquinaria');

Route::get('/ubicacion/search/{term}', 'UbicacionController@search');

Route::resource('ubicacion', 'UbicacionController');

Route::resource('admin','AdminController');


Route::resource('maquinarias.mcorrectivos', 'McorrectivosController' );

Route::resource('maquinarias.receta', 'RecetasController' );

Route::resource('maquinarias.movimientos', 'MovimientosController' );

Route::get('/maquinarias/{idMaquinaria}/receta/{idReceta}/detalle/create', 'DetalleRecetaController@create');
Route::post('/detalle', 'DetalleRecetaController@store');
Route::delete('/detalle', 'DetalleRecetaController@destroy');

Route::resource('obras','ObrasController');

Route::resource('proveedores','ProveedoresController');

Route::get('/obras/search/{term}', 'ObrasController@search');
Route::post('/obras/save', 'ObrasController@save');

Route::get('/proveedores/search/{term}', 'ProveedoresController@search');
Route::post('/proveedores/save', 'ProveedoresController@save');

Route::resource('ordencompra','OrdenCompraController');

Route::resource('consumiblesAlmacen','ConsumiblesAlmacenController');

Route::get('/consumiblesAlmacen/search/{term}', 'ConsumiblesAlmacenController@search');
Route::post('/consumiblesAlmacen/save', 'ConsumiblesAlmacenController@save');

Route::resource('consumibles', 'ConsumiblesAlmacenController');

Route::resource('pecosas','PecosasController');	

Route::get('/ordencompra/search/{term}', 'OrdenCompraController@search');

Route::get('/detalles_oc/search/{term}', 'OrdenCompraController@search_detalle_oc');

Route::post('/ordencompra/update/{id}','OrdenCompraController@update');

Route::resource('stockalmacen','StockAlmacenController');

Route::resource('valeconsumo','ValeConsumoController');
Route::post('/valeconsumo/update/{id}','ValeConsumoController@update');

sigma_final/app/Movimiento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movimiento extends Model
{
    protected $table = 'movimientos';

    protected $primaryKey = 'movimiento_id';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'movimiento_id',
        'maquinaria_id',
        'fecha_entrada',
        'fecha_salida',
        'descripcion',
        'obra_institucion',
        'provincia_id',
        'doc_asignacion',
        'turno'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at',
    ];

    public function maquinaria(){
        return $this->belongsTo('App\Maquinaria' , 'maquinaria_id');
    }


}

sigma_final/app/Http/Controllers/MovimientosController.php
<?php 
 
namespace App\Http\Controllers; 
 
use App\Movimiento; 
use App\Maquinaria;
use App\Provincia;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
 
class MovimientosController extends Controller 
{ 
    /** 
     * Display a listing of the resource. 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function index() 
    { 
 
    } 
 
    /** 
     * Show the form for creating a new resource. 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function create($idMaquinaria) 
    {

        $provincias= Provincia::select('nombre','provincia_id')->get();
        return view('movimientos.create', [ 'maquinaria' => Maquinaria::findOrFail($idMaquinaria),'provincias' =>$provincias]);
    } 
 
    /** 
     * Store a newly created resource in storage. 
     * 
     * @param  \Illuminate\Http\Request  $request 
     * @return \Illuminate\Http\Response 
     */ 
    public function store(Request $request, $idMaquinaria) 
    {

        $this->validate($request , [
            'fecha_entrada'     => 'required',
            'fecha_salida'      => 'required',
            'descripcion'       => 'required',
            'obra_institucion'  => 'required',
            'provincia_id'      => 'required',
            'doc_asignacion'    => 'required',
            'turno'             => 'required',

        ]);

        $maquinaria = Maquinaria::findOrFail($idMaquinaria); 
 
        $movimiento = new Movimiento(); 
        $movimiento->maquinaria_id = $idMaquinaria; 
        $movimiento->fecha_entrada = $request->get('fecha_entrada'); 
        $movimiento->fecha_salida = $request->get('fecha_salida'); 
        $movimiento->descripcion = $request->get('descripcion'); 
        $movimiento->obra_institucion  = $request->get('obra_institucion'); 
        $movimiento->provincia_id  = $request->get('provincia_id')+1;
        $movimiento->doc_asignacion  = $request->get('doc_asignacion'); 
        $movimiento->turno  = $request->get('turno'); 
 
        $movimiento->save(); 
        return redirect()->route('maquinarias.show' , $idMaquinaria); 
    } 
 
    /** 
     * Display the specified resource. 
     * 
     * @param  \App\Movimiento  $movimiento 
     * @return \Illuminate\Http\Response 
     */ 
    public function show(Movimiento $movimiento) 
    { 
        // 
    } 
 
    /** 
     * Show the form for editing the specified resource. 
     * 
     * @param  \App\Movimiento  $movimiento 
     * @return \Illuminate\Http\Response 
     */ 
    public function edit($idMaquinaria , $id) 
    {
        $provincias= Provincia::select('nombre','provincia_id')->get();
        $movimiento = Movimiento::where('maquinaria_id',$idMaquinaria)->where('movimiento_id',$id)->first(); 
        $maquinaria = $movimiento->maquinaria;
        return view('movimientos.edit', ['mov'=> $movimiento,'provincias' =>$provincias ,'maquinaria' => $maquinaria]);
    } 
 
    /** 
     * Update the specified resource in storage. 
     * 
     * @param  \Illuminate\Http\Request  $request 
     * @param  \App\Movimiento  $movimiento 
     * @return \Illuminate\Http\Response 
     */ 
    public function update(Request $request, $idMaquinaria, $id) 
    {

        $this->validate($request , [
            'fecha_entrada'     => 'required',
            'fecha_salida'      => 'required',
            'descripcion'       => 'required',
            'obra_institucion'  => 'required',
            'provincia_id'      => 'required',
            'doc_asignacion'    => 'required',
            'turno'             => 'required',

        ]);
 
        $movimiento = Movimiento::where('maquinaria_id',$idMaquinaria)->where('movimiento_id',$id)->first(); 
        $movimiento->maquinaria_id = $idMaquinaria; 
        $movimiento->fecha_entrada = $request->get('fecha_entrada'); 
        $movimiento->fecha_salida = $request->get('fecha_salida'); 
        $movimiento->descripcion = $request->get('descripcion'); 
        $movimiento->obra_institucion  = $request->get('obra_institucion'); 
        $movimiento->provincia_id  = $request->get('provincia_id')+1;
        $movimiento->doc_asignacion  = $request->get('doc_asignacion'); 
        $movimiento->turno  = $request->get('turno'); 
 
        $movimiento->save(); 
        return redirect()->route('maquinarias.show' , $idMaquinaria); 
    } 
 
    /** 
     * Remove the specified resource from storage. 
     * 
     * @param  \App\Movimiento  $movimiento 
     * @return \Illuminate\Http\Response 
     */ 
    public function destroy($idMaquinaria,$id ) 
    { 
        //$maquinaria = Maquinaria::findOrFail($idMaquinaria); 
        $movimiento = Movimiento::where('maquinaria_id',$idMaquinaria)->where('movimiento_id',$id)->first(); 
 
        $movimiento->delete(); 
        return redirect()->route('maquinarias.show' , $idMaquinaria); 
 
 
    } 
} 

sigma_final/resources/views/movimientos/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="row  justify-content-md-center" >
    <div class="col-md-7">
      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
    </div>
  </div>
  <div class="row  justify-content-md-center" >
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="d-flex justify-content-between align-items-center">
            
            <div>
              <h2>{{ $maquinaria->tipo . ' ' . $maquinaria->modelo . ' ' . $maquinaria->nro_registro }}</h2>
            </div>
            <div>
              <h4><strong>Horometro: </strong>{{ $maquinaria->horometro }}</h4>
            </div>
          </div>
        </div>
        <div class="card-block">
          {!! Form::open([
          'route' => ['maquinarias.movimientos.store' , $maquinaria->maquinaria_id],
          'method' => 'POST'
          ]) !!}
          
          <div class="form-group row">
            {!! Form::label('fecha_entrada' , 'Fecha de Entrada:' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::date('fecha_entrada' , \Carbon\Carbon::now() , ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('fecha_salida' , 'Fecha de Salida:' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::date('fecha_salida' ,null, ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('obra_institucion' , 'Obra | Institución :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::text('obra_institucion' , null , ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('provincia_id' , 'Provincia :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::select('provincia_id', $provincias->pluck('nombre'),$provincias->pluck('provincia_id'),['class' => 'form-control'])!!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('doc_asignacion' , 'Documento de Asignación :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::text('doc_asignacion' , null , ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('descripcion' , 'Descripción :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::text('descripcion' , null , ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('turno' , 'Turno :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              <div class="form-check form-check-inline">
                <label class="form-check-label">
                  {!! Form::radio('turno' , 1 , true , [ 'class' => 'form-check-input'])!!}
                  1 turno
                </label>
              </div>
              <div class="form-check form-check-inline">
                <label class="form-check-label">
                  {!! Form::radio('turno' , 2 , false , [ 'class' => 'form-check-input']) !!}
                  2 turnos
                </label>
              </div>
            </div>
          </div>
          
          
          <div class="form-group">
            {!! Form::submit('Guardar' , ['class' => 'btn btn-success']) !!}
          </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

sigma_final/resources/views/movimientos/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="row  justify-content-md-center" >
    <div class="col-md-7">
      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
    </div>
  </div>
  <div class="row  justify-content-md-center" >
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="d-flex justify-content-between align-items-center">
            
            <div>
              <h2>{{ $maquinaria->tipo . ' ' . $maquinaria->modelo . ' ' . $maquinaria->nro_registro }}</h2>
            </div>
            <div>
              <h4><strong>Horometro: </strong>{{ $maquinaria->horometro }}</h4>
            </div>
          </div>
        </div>
        <div class="card-block">
          {!! Form::open([
          'url' => '/maquinarias/' . $mov->maquinaria_id . '/movimientos/' . $mov->movimiento_id,
          'method' => 'PUT'
          ]) !!}
          
          
          <div class="form-group row">
            {!! Form::label('fecha_entrada' , 'Fecha de Entrada:' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::date('fecha_entrada' , $mov->fecha_entrada , ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('fecha_salida' , 'Fecha de Salida:' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::date('fecha_salida' ,$mov->fecha_salida, ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('obra_institucion' , 'Obra | Institución :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::text('obra_institucion' , $mov->obra_institucion , ['class' => 'form-control']) !!}
            </div>
          </div>
          <div class="form-group row">
            {!! Form::label('provincia_id' , 'Provincia :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::select('provincia_id', $provincias->pluck('nombre'),$provincias->pluck('provincia_id'),['class' => 'form-control'])!!}
            </div>
          </div>
          <div class="form-group row">
            {!! Form::label('doc_asignacion' , 'Documento de Asignación :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::text('doc_asignacion' , $mov->doc_asignacion , ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('descripcion' , 'Descripción :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              {!! Form::text('descripcion' , $mov->descripcion , ['class' => 'form-control']) !!}
            </div>
          </div>
          
          <div class="form-group row">
            {!! Form::label('turno' , 'Turno :' , ['class' => 'col-form-label col-sm-3']) !!}
            <div class="col-sm-9">
              <div class="form-check form-check-inline">
                <label class="form-check-label">
                  {!! Form::radio('turno' , 1 , ($mov->turno == 1) ? true : false , [ 'class' => 'form-check-input'])!!}
                  1 turno
                </label>
              </div>
              <div class="form-check form-check-inline">
                <label class="form-check-label">
                  {!! Form::radio('turno' , 2 , ($mov->turno == 2) ? true : false , [ 'class' => 'form-check-input']) !!}
                  2 turnos
                </label>
              </div>
            </div>
          </div>
          
          <div class="form-group">
            {!! Form::submit('Guardar' , ['class' => 'btn btn-success']) !!}
          </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

sigma_final/resources/views/movimientos/show.blade.php
<div class="mt-2">
	<div class="row ">
		<div class="col">
			<div class="d-flex mb-3 justify-content-end">
				<a href="{{ route('maquinarias.movimientos.create' , $maquinaria->maquinaria_id) }}" class="btn btn-primary"><i class="fa fa-plus"></i> Agregar</a>
			</div>
		
		</div>
	</div>
	<div class="table-responsive">
		<table class="table">
			<thead class="thead-inverse">
				<tr>
					<th>Fecha de Entrada</th>
					<th>Fecha de Salida</th>
					<th>Obra / Institución</th>
					<th>Provincia</th>
					<th>Nro de Asignación</th>
					<th>Turno</th>
					<th>Descripción</th>
					<th colspan="2">Acciones</th>
				</tr>
			</thead>
			<tbody>
				@foreach($mov as $mo)
				<tr>
					<td>{{ $mo->fecha_entrada }}</td>
					<td>{{ $mo->fecha_salida }}</td>
					<td>{{ $mo->obra_institucion }}</td>
					<td>{{ $mo->nombre }}</td>
					<td>{{ $mo->doc_asignacion }}</td>
					<td>{{ $mo->turno }}</td>
					<td>{{ $mo->descripcion }}</td>
					
					<td>
						<a href="{{ route('maquinarias.movimientos.edit' , ['maquinaria' => $mo->maquinaria_id ,
						'movimiento' => $mo->movimiento_id]) }}" class="btn btn-success"><i class="fa fa-pencil"></i></a>
					</td>
					<td>
						<a>
							{!! Form::open([
							'method' => 'DELETE',
							'url' => '/maquinarias/' . $maquinaria->maquinaria_id . '/movimientos/' . $mo->movimiento_id ]) !!}
							{!! Form::button('<i class="fa fa-trash"></i>',  ['class' => 'btn btn-danger' , 'type' => 'submit']) !!}
							{!! Form::close() !!}
						</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>