sigma_final/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Redirect::to('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/maquinarias/list', 'MaquinariasController@data');

Route::resource('maquinarias', 'MaquinariasController');
Route::resource('maquinarias.mpreventivos', 'MpreventivosController' );

Route::get('/ubicacion/provincia/{id}', 'UbicacionController@maquinarias');
Route::get('/ubicacion/maquinaria/{serie}', 'UbicacionController@buscarMaquinaria');

Route::get('/ubicacion/search/{term}', 'UbicacionController@search');

Route::resource('ubicacion', 'UbicacionController');

Route::resource('admin','AdminController');


Route::resource('maquinarias.mcorrectivos', 'McorrectivosController' );

Route::resource('maquinarias.receta', 'RecetasController' );

Route::resource('maquinarias.movimientos', 'MovimientosController' );

Route::get('/maquinarias/{idMaquinaria}/receta/{idReceta}/detalle/create', 'DetalleRecetaController@create');
Route::post('/detalle', 'DetalleRecetaController@store');
Route::delete('/detalle', 'DetalleRecetaController@destroy');

Route::resource('obras','ObrasController');

Route::resource('proveedores','ProveedoresController');

Route::get('/obras/search/{term}', 'ObrasController@search');
Route::post('/obras/save', 'ObrasController@save');

Route::get('/proveedores/search/{term}', 'ProveedoresController@search');
Route::post('/proveedores/save', 'ProveedoresController@save');

Route::resource('ordencompra','OrdenCompraController');

Route::resource('consumiblesAlmacen','ConsumiblesAlmacenController');

Route::get('/consumiblesAlmacen/search/{term}', 'ConsumiblesAlmacenController@search');
Route::post('/consumiblesAlmacen/save', 'ConsumiblesAlmacenController@save');

Route::resource('consumibles', 'ConsumiblesAlmacenController');

Route::resource('pecosas','PecosasController');	

Route::get('/ordencompra/search/{term}', 'OrdenCompraController@search');

Route::get('/detalles_oc/search/{term}', 'OrdenCompraController@search_detalle_oc');

Route::post('/ordencompra/update/{id}','OrdenCompraController@update');

Route::resource('stockalmacen','StockAlmacenController');

Route::resource('valeconsumo','ValeConsumoController');
Route::post('/valeconsumo/update/{id}','ValeConsumoController@update');

sigma_final/app/Http/Controllers/ConsumiblesAlmacenController.php
<?php

namespace App\Http\Controllers;

use App\ConsumibleAlmacen;
use Illuminate\Http\Request;
use Response;

class ConsumiblesAlmacenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('consumiblesAlmacen.index', ['consumiblesAlmacen'=>ConsumibleAlmacen::all()]);
    }

    public function search($term)
    {
      $consumible_almacen = ConsumibleAlmacen::where('codigo', 'like', '%'.$term.'%')
        ->orWhere('marca', 'like', '%'.$term.'%')
        ->orWhere('descripcion', 'like', '%'.$term.'%')
        ->get();
      return Response::json(['items' => $consumible_almacen]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('consumiblesAlmacen.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $consumibleAlmac = new ConsumibleAlmacen();
        $consumibleAlmac->codigo = $request->get('codigo');
        $consumibleAlmac->descripcion = $request->get('descripcion');
        $consumibleAlmac->unidad = $request->get('unidad');
        $consumibleAlmac->marca = $request->get('marca');
        $consumibleAlmac->precio_ref = $request->get('precio_ref');
        $consumibleAlmac->save();
        return redirect()->route('consumibles.index');
    }

    public function save(Request $request)
    {
        $consumibleAlmac = new ConsumibleAlmacen();
        $consumibleAlmac->codigo = $request->get('codigo');
        $consumibleAlmac->descripcion = $request->get('descripcion');
        $consumibleAlmac->unidad = $request->get('unidad');
        $consumibleAlmac->marca = $request->get('marca');
        $consumibleAlmac->precio_ref = $request->get('precio_ref');
        $consumibleAlmac->tipo = $request->get('tipo');
        $consumibleAlmac->save();

        return Response::json(['result'=>$consumibleAlmac], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $consumibleAlmac = ConsumibleAlmacen::where('consumible_almac_id',$id)->first();
        return view('consumiblesAlmacen.edit', ['consumiblesAlmacen'=> $consumibleAlmac]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $consumibleAlmac = ConsumibleAlmacen::findOrFail($id);
        $consumibleAlmac->codigo = $request->get('codigo');
        $consumibleAlmac->descripcion = $request->get('descripcion');
        $consumibleAlmac->unidad = $request->get('unidad');
        $consumibleAlmac->marca = $request->get('marca');
        $consumibleAlmac->precio_ref = $request->get('precio_ref');
        $consumibleAlmac->tipo = $request->get('tipo');
        $consumibleAlmac->save();
        return redirect()->route('consumibles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
    }
}

sigma_final/resources/views/consumiblesAlmacen/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="row  justify-content-md-center" >
    <div class="col-md-7">
      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
    </div>
  </div>
  <div class="row  justify-content-md-center" >
    <div class="col-md-7">
      {!! Form::open([
      'route' => ['consumiblesAlmacen.store'],
      'method' => 'POST'
      ]) !!}
      
      <div class="form-group row">
        {!! Form::label('codigo' , 'Código:' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('codigo' , null , ['class' => 'form-control']) !!}
        </div>
      </div>
      
      <div class="form-group row">
        {!! Form::label('descripcion' , 'Descripcion :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('descripcion' , null , ['class' => 'form-control']) !!}
        </div>
      </div>
      <div class="form-group row">
        {!! Form::label('unidad' , 'Unidad :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('unidad' , null , ['class' => 'form-control']) !!}
        </div>
      </div>
      <div class="form-group row">
        {!! Form::label('marca' , 'Marca :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('marca' , null , ['class' => 'form-control']) !!}
        </div>
      </div>
      <div class="form-group row">
        {!! Form::label('precio_ref' , 'Precio Referencial :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('precio_ref' , null , ['class' => 'form-control']) !!}
        </div>
      </div>
      
      <div class="form-group row">
        {!! Form::label('tipo' , 'Tipo :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          <select name="tipo" id="tipo" class="form-control">
            <option value="1">Filtro</option>
            <option value="2">Lubricante</option>
            <option value="1">Elememnto de desgaste</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        {!! Form::submit('Guardar' , ['class' => 'btn btn-success']) !!}
      </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>
@endsection

sigma_final/resources/views/consumiblesAlmacen/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="row  justify-content-md-center" >
    <div class="col-md-7">
      @if (count($errors) > 0)
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
    </div>
  </div>
  <div class="row  justify-content-md-center" >
    <div class="col-md-7">
      {!! Form::open([
      'route' => ['consumiblesAlmacen.update' , $consumiblesAlmacen->consumible_almac_id ],
      'method' => 'PUT'
      ]) !!}
      
      <div class="form-group row">
        {!! Form::label('codigo' , 'Código:' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('codigo' , $consumiblesAlmacen->codigo , ['class' => 'form-control']) !!}
        </div>
      </div>
      
      <div class="form-group row">
        {!! Form::label('descripcion' , 'Descripcion :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('descripcion' , $consumiblesAlmacen->descripcion , ['class' => 'form-control']) !!}
        </div>
      </div>
      <div class="form-group row">
        {!! Form::label('unidad' , 'Unidad :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('unidad' , $consumiblesAlmacen->unidad , ['class' => 'form-control']) !!}
        </div>
      </div>
      <div class="form-group row">
        {!! Form::label('marca' , 'Marca :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('marca' , $consumiblesAlmacen->marca , ['class' => 'form-control']) !!}
        </div>
      </div>
      <div class="form-group row">
        {!! Form::label('precio_ref' , 'Precio Referencial :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          {!! Form::text('precio_ref' , $consumiblesAlmacen->precio_ref , ['class' => 'form-control']) !!}
        </div>
      </div>
      <div class="form-group row">
        {!! Form::label('tipo' , 'Tipo :' , ['class' => 'col-form-label col-sm-3']) !!}
        <div class="col-sm-9">
          <select name="tipo" id="tipo" class="form-control">

            <option value="1" {{ ($consumiblesAlmacen->tipo == 1 ) ? 'selected' : '' }}>Filtro</option>
            <option value="2" {{ ($consumiblesAlmacen->tipo == 2 ) ? 'selected' : '' }}>Lubricante</option>
            <option value="3" {{ ($consumiblesAlmacen->tipo == 3 ) ? 'selected' : '' }} >Elememnto de desgaste</option>
          </select>
        </div>
      </div>
      
      <div class="form-group">
        {!! Form::submit('Guardar' , ['class' => 'btn btn-success']) !!}
      </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>
@endsection

sigma_final/resources/views/consumiblesAlmacen/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					Consumibles
				</div>
				<div class="card-block">
					<div class="row ">
						<div class="col">
							<div class="d-flex mb-3 justify-content-end">
								<a href="{{ route('consumibles.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Agregar</a>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<!--<div class="table-responsive">-->
							
							<table id="consumibles" class="display" cellspacing="0" width="100%">
								<thead class="thead-inverse">
									<tr>
										<th>#</th>
										<th>Código</th>
										<th>Descripcion</th>
										<th>Unidad</th>
										<th>Precio Referencial</th>
										<th>Marca</th>
										<th>Tipo</th>
										<th></th>
									</tr>
								</thead>
								
								<tbody>
									@foreach($consumiblesAlmacen as $c)
									<tr>
										<td scope="row">{{ $loop->iteration }}</td>
										<td>{{ $c->codigo }}</td>
										<td>{{ $c->descripcion }}</td>
										<td>{{ $c->unidad }}</td>
										<td>{{ $c->precio_ref }}</td>
										<td>{{ $c->marca }}</td>
										<td>
											@if($c->tipo == 1)
											Filtro
											@elseif($c->tipo == 2)
											Lubricante
											@elseif($c->tipo == 3)
											Elemento de desgaste
											@endif
										</td>

										<td><a href="{{ route('consumibles.edit' , $c->consumible_almac_id) }}" class="btn btn-success">Editar</a>
										</td>
						
									</tr>
									@endforeach
								</tbody>
							</table>
							
							<!--</div>-->

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
<script>
	$(document).ready(function() {
		var table = $('#consumibles').DataTable({
			dom: 'Bfrtip',
	        buttons: [
	            'pdf'
	        ],
			"scrollX": true,
		});
	} );
</script>
@endsection