sigma_final/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Redirect::to('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/maquinarias/list', 'MaquinariasController@data');

Route::resource('maquinarias', 'MaquinariasController');
Route::resource('maquinarias.mpreventivos', 'MpreventivosController' );

Route::get('/ubicacion/provincia/{id}', 'UbicacionController@maquinarias');
Route::get('/ubicacion/maquinaria/{serie}', 'UbicacionController@buscarMaquinaria');

Route::get('/ubicacion/search/{term}', 'UbicacionController@search');

Route::resource('ubicacion', 'UbicacionController');

Route::resource('admin','AdminController');


Route::resource('maquinarias.mcorrectivos', 'McorrectivosController' );

Route::resource('maquinarias.receta', 'RecetasController' );

Route::resource('maquinarias.movimientos', 'MovimientosController' );

Route::get('/maquinarias/{idMaquinaria}/receta/{idReceta}/detalle/create', 'DetalleRecetaController@create');
Route::post('/detalle', 'DetalleRecetaController@store');
Route::delete('/detalle', 'DetalleRecetaController@destroy');

Route::resource('obras','ObrasController');

Route::resource('proveedores','ProveedoresController');

Route::get('/obras/search/{term}', 'ObrasController@search');
Route::post('/obras/save', 'ObrasController@save');

Route::get('/proveedores/search/{term}', 'ProveedoresController@search');
Route::post('/proveedores/save', 'ProveedoresController@save');

Route::resource('ordencompra','OrdenCompraController');

Route::resource('consumiblesAlmacen','ConsumiblesAlmacenController');

Route::get('/consumiblesAlmacen/search/{term}', 'ConsumiblesAlmacenController@search');
Route::post('/consumiblesAlmacen/save', 'ConsumiblesAlmacenController@save');

Route::resource('consumibles', 'ConsumiblesAlmacenController');

Route::resource('pecosas','PecosasController');	

Route::get('/ordencompra/search/{term}', 'OrdenCompraController@search');

Route::get('/detalles_oc/search/{term}', 'OrdenCompraController@search_detalle_oc');

Route::post('/ordencompra/update/{id}','OrdenCompraController@update');

Route::resource('stockalmacen','StockAlmacenController');

Route::resource('valeconsumo','ValeConsumoController');
Route::post('/valeconsumo/update/{id}','ValeConsumoController@update');

sigma_final/app/Mpreventivo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mpreventivo extends Model
{
    protected $table = 'm_preventivos';

    protected $primaryKey = 'mpreventivo_id';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'mp',
        'obra_institucion',
        'nro_reporte',
        'mecanico',
        'fecha_ejecución',
        'horometro_aprox',
        'fecha_aprox',
        'maquinaria_id',
        'usuario_id',
        'realizado',
        'pase',
        'mpreventivo_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at',
    ];

    public function maquinaria(){
        return $this->belongsTo('App\Maquinaria' , 'maquinaria_id');
    }
}

sigma_final/app/Http/Controllers/MpreventivosController.php
<?php

namespace App\Http\Controllers;

use App\Mpreventivo;
use App\Maquinaria;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MpreventivosController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('checkStatusMPreventivo')->only('edit' , 'update' , 'destroy');
   
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        
        //return $mpreventivo;
        return Mpreventivo::where('mpreventivo_id', $id)->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        return view('mpreventivos.create' , [ 'maquinaria' => Maquinaria::findOrFail($id) ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request , $idMaquinaria)
    {

        $this->validate($request , [
            'mp' => 'required:numeric',
            'obra_institucion' => 'required',
            'nro_reporte'=> 'required',
            'mecanico' => 'required',
            'fecha_ejecución' => 'required|date',
                  
        ]);



        $maquinaria = Maquinaria::findOrFail($idMaquinaria);
        $mpreventivo = new Mpreventivo();

        if(!($request->get('mp') > $maquinaria->horometro)){
            return redirect()->back()->with('flash_message' , 'El mp debe ser mayor al horometro')->withInput();
        }

        $mpreventivo->mp                = $request->get('mp');
        $mpreventivo->obra_institucion  = $request->get('obra_institucion');
        $mpreventivo->horometro         = $mpreventivo->mp - $maquinaria->horometro;
        $mpreventivo->nro_reporte       = $request->get('nro_reporte');
        $mpreventivo->mecanico          = $request->get('mecanico');
        $mpreventivo->fecha_ejecución   = $request->get('fecha_ejecución');
        $mpreventivo->maquinaria_id     = $idMaquinaria;
        $mpreventivo->usuario_id        = Auth::user()->id;
        $mpreventivo->realizado         = $request->get('realizado');
        $mpreventivo->pase              = $request->get('pase');
        
        $mpreventivo->horometro_aprox   = $mpreventivo->horometro + $maquinaria->horometro;
        $date = Carbon::parse($mpreventivo->fecha_ejecución);
        $mpreventivo->fecha_aprox       = $date->addMonth(); 
        
        if($mpreventivo->realizado != null){
            $mpreventivo->status = true;
            $maquinaria->horometro = $mpreventivo->horometro + $maquinaria->horometro;
            $maquinaria->save();
        }
        $mpreventivo->save();
            
        return redirect()->route('maquinarias.show' , $idMaquinaria);
        
        

       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($idMaquinaria , $id)
    {
        //$this->middleware('checkStatusMPreventivo');
        $mpreventivo = Mpreventivo::where('maquinaria_id' , $idMaquinaria)->where('mpreventivo_id' , $id)->first();
        $maquinaria = $mpreventivo->maquinaria;
        return view('mpreventivos.edit' , ['mp' => $mpreventivo , 'maquinaria' => $maquinaria]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $idMaquinaria, $id)
    {
        //$this->middleware('checkStatusMPreventivo');
         $this->validate($request , [
            'mp' => 'required:numeric',
            'obra_institucion' => 'required',
            'nro_reporte'=> 'required',
            'mecanico' => 'required',
            'fecha_ejecución' => 'required|date',
        ]);
        $maquinaria = Maquinaria::findOrFail($idMaquinaria);
        $mpreventivo = Mpreventivo::where('maquinaria_id' , $idMaquinaria)->where('mpreventivo_id' , $id)->first();

        if(!($request->get('mp') > $maquinaria->horometro)){
            return redirect()->back()->with('flash_message' , 'El mp debe ser mayor al horometro')->withInput();;
        }

        $oldRealizado = $mpreventivo->realizado;
        $mpreventivo->mp                = $request->get('mp');
        
        $mpreventivo->obra_institucion  = $request->get('obra_institucion');
        $mpreventivo->nro_reporte       = $request->get('nro_reporte');
        $mpreventivo->mecanico          = $request->get('mecanico');
        $mpreventivo->fecha_ejecución   = $request->get('fecha_ejecución');
        $mpreventivo->maquinaria_id     = $idMaquinaria;
        $mpreventivo->usuario_id        = Auth::user()->id;
        $mpreventivo->realizado         = $request->get('realizado');
        $mpreventivo->pase              = $request->get('pase');
        $date = Carbon::parse($mpreventivo->fecha_ejecución);
        $mpreventivo->fecha_aprox       = $date->addMonth(); 
        
        
        if($oldRealizado != null){
            $maquinaria->horometro = $maquinaria->horometro - $mpreventivo->horometro;
        }
        $mpreventivo->horometro         = $mpreventivo->mp - $maquinaria->horometro;
        if($mpreventivo->realizado != null){
            $mpreventivo->status = true;
            $maquinaria->horometro = $maquinaria->horometro + $mpreventivo->horometro;    
             
        }
        if($mpreventivo->mp == $maquinaria->horometro){
            $mpreventivo->horometro_aprox   = $mpreventivo->mp;
        }else{
            $mpreventivo->horometro_aprox   = $mpreventivo->horometro + $maquinaria->horometro;
        }
        $maquinaria->save();
        $mpreventivo->save();  
        
        //$mpreventivo->horometro         = $mpreventivo->mp - $maquinaria->horometro;
        //
        
        
        return redirect()->route('maquinarias.show' , $idMaquinaria);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($idMaquinaria , $id)
    {
        $maquinaria = Maquinaria::findOrFail($idMaquinaria);
        $mpreventivo = Mpreventivo::where('maquinaria_id' , $idMaquinaria)->where('mpreventivo_id' , $id)->first();
        if($mpreventivo->realizado != null){
            $maquinaria->horometro = $maquinaria->horometro - $mpreventivo->horometro;
            $maquinaria->save();
        }
        
        $mpreventivo->delete();
        

        

        return redirect()->route('maquinarias.show' , $idMaquinaria);
    }
}

sigma_final/resources/views/mpreventivos/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row  justify-content-md-center" >
		<div class="col-md-7">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if (session('flash_message'))
			<div class="alert alert-danger">
				<ul>
					<li>{{ session('flash_message') }}</li>
				</ul>
			</div>
			@endif
		</div>
	</div>
	<div class="row  justify-content-md-center" >
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<di class="d-flex justify-content-between align-items-center">
					
					<div>
						<h2>{{ $maquinaria->tipo . ' ' . $maquinaria->modelo . ' ' . $maquinaria->nro_registro }}</h2>
					</div>
					<div>
						<h4><strong>Horometro: </strong>{{ $maquinaria->horometro }}</h4>
					</div>
				</div>
				<div class="card-block">
					{!! Form::open([
					'route' => ['maquinarias.mpreventivos.store' , $maquinaria->maquinaria_id],
					'method' => 'POST'
					]) !!}
					<div class="form-group row">
						{!! Form::label('mp' , 'MP :' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::number('mp' , null , ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group row">
						{!! Form::label('obra_institucion' , 'Obra | Institución ;' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::text('obra_institucion' , null , ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group row">
						{!! Form::label('nro_reporte' , 'Nro de reporte :' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::text('nro_reporte' , null , ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group row">
						{!! Form::label('mecanico' , 'Mecánico :' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::text('mecanico' , null , ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group row">
						{!! Form::label('fecha_ejecución' , 'Fecha de ejecución :' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::date('fecha_ejecución' , \Carbon\Carbon::now() , ['class' => 'form-control']) !!}
						</div>
					</div>
					<!--<div class="form-group row">
								{!! Form::label('horometro_aprox' , 'Horometro aproximado :' , ['class' => 'col-form-label col-sm-3']) !!}
								<div class="col-sm-9">
											{!! Form::number('horometro_aprox' , null , ['class' => 'form-control']) !!}
								</div>
					</div>
					<div class="form-group row">
								{!! Form::label('fecha_aprox' , 'Fecha aproxiamada :' , ['class' => 'col-form-label col-sm-3']) !!}
								<div class="col-sm-9">
											{!! Form::date('fecha_aprox' , null , ['class' => 'form-control']) !!}
								</div>
					</div>-->
					<div class="form-group row">
						<label class="col-sm-3 col-form-label">Realizado</label>
						<div class="col-sm-9">
							<div class="form-check form-check-inline">
								<label class="form-check-label">
									{!! Form::checkbox('realizado' , 1 , false , [ 'class' => 'form-check-input' , 'id' =>'realizado' ]) !!}
								</label>
								<div id="show-realizado" class="alert alert-warning" style="display: none">
									Ya no podras editar o eliminar este registro
								</div>
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-3 col-form-label">Pase</label>
						<div class="col-sm-9">
							<div class="form-check form-check-inline">
								<label class="form-check-label">
									{!! Form::checkbox('pase' , 1 , false , [ 'class' => 'form-check-input']) !!}
								</label>
							</div>
						</div>
					</div>
					
					
					<div class="form-group">
						{!! Form::submit('Guardar' , ['class' => 'btn btn-success']) !!}
					</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
<script>
	$('#realizado').change(function(){
		if($(this).is(':checked')){
			$('#show-realizado').show();
		}else{
			$('#show-realizado').hide();
		}
	});
</script>
@endsection

sigma_final/resources/views/mpreventivos/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row  justify-content-md-center" >
		<div class="col-md-7">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if (session('flash_message'))
			<div class="alert alert-danger">
				<ul>
					<li>{{ session('flash_message') }}</li>
				</ul>
			</div>
			@endif
		</div>
	</div>
	<div class="row  justify-content-md-center" >
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="d-flex justify-content-between align-items-center">
						
						<div>
							<h2>{{ $maquinaria->tipo . ' ' . $maquinaria->modelo . ' ' . $maquinaria->nro_registro }}</h2>
						</div>
						<div>
							<h4><strong>Horometro: </strong>{{ $maquinaria->horometro }}</h4>
						</div>
					</div>
				</div>
				<div class="card-block">
					{!! Form::open([
					'method' => 'PUT',
					'url' => '/maquinarias/' . $mp->maquinaria_id . '/mpreventivos/' . $mp->mpreventivo_id,
					]) !!}
					<div class="form-group row">
						{!! Form::label('mp' , 'MP :' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::number('mp' , $mp->mp , ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group row">
						{!! Form::label('obra_institucion' , 'Obra | Institución ;' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::text('obra_institucion' , $mp->obra_institucion , ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group row">
						{!! Form::label('nro_reporte' , 'Nro de reporte :' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::text('nro_reporte' , $mp->nro_reporte , ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group row">
						{!! Form::label('mecanico' , 'Mecánico :' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::text('mecanico' , $mp->mecanico , ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group row">
						{!! Form::label('fecha_ejecución' , 'Fecha de ejecución :' , ['class' => 'col-form-label col-sm-3']) !!}
						<div class="col-sm-9">
							{!! Form::date('fecha_ejecución' , $mp->fecha_ejecución , ['class' => 'form-control']) !!}
						</div>
					</div>
					<!--<div class="form-group row">
									{!! Form::label('horometro_aprox' , 'Horometro aproximado :' , ['class' => 'col-form-label col-sm-3']) !!}
									<div class="col-sm-9">
													{!! Form::number('horometro_aprox' , $mp->horometro_aprox , ['class' => 'form-control']) !!}
									</div>
					</div>
					<div class="form-group row">
									{!! Form::label('fecha_aprox' , 'Fecha aproxiamada :' , ['class' => 'col-form-label col-sm-3']) !!}
									<div class="col-sm-9">
													{!! Form::date('fecha_aprox' , $mp->fecha_aprox , ['class' => 'form-control']) !!}
									</div>
					</div>-->
					<div class="form-group row">
						<label class="col-sm-3 col-form-label">Realizado</label>
						<div class="col-sm-9">
							<div class="form-check form-check-inline">
								<label class="form-check-label">
									
									{!! Form::checkbox('realizado' , 1 , (isset($mp->realizado)) ? true : false , [ 'class' => 'form-check-input' , 'id' =>'realizado']) !!}
									
								</label>
								<div id="show-realizado" class="alert alert-warning" style="display: none">
									Ya no podras editar o eliminar este registro
								</div>
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-3 col-form-label">Pase</label>
						<div class="col-sm-9">
							<div class="form-check form-check-inline">
								<label class="form-check-label">
									
									{!! Form::checkbox('pase' , 1 , (isset($mp->pase)) ? true : false , [ 'class' => 'form-check-input']) !!}
								</label>
							</div>
						</div>
					</div>
					
					
					<div class="form-group">
						{!! Form::submit('Guardar' , ['class' => 'btn btn-success']) !!}
					</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
<script>
	$('#realizado').change(function(){
		if($(this).is(':checked')){
			$('#show-realizado').show();
		}else{
			$('#show-realizado').hide();
		}
	});
</script>
@endsection

sigma_final/resources/views/mpreventivos/show.blade.php
<div class="mt-2">
	<div class="row ">
		<div class="col">
			<div class="d-flex mb-3 justify-content-end">
				<a href="{{ route('maquinarias.mpreventivos.create' , $maquinaria->maquinaria_id) }}" class="btn btn-primary {{ ($receta != null ? '' : 'disabled')}}"><i class="fa fa-plus"></i> Agregar</a>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table">
			<thead class="thead-inverse">
				<tr>
					<th>MP</th>
					<th>Obra | Institución</th>
					<th>Mecanico</th>
					<th>Nro de Reporte</th>
					<th>Fecha de Ejecución</th>
					<th>Horometro Aproximado</th>
					<th>Fecha Aproximada</th>
					<th>Realizado</th>
					<th>Pase</th>
					<th colspan="2">Acciones</th>
				</tr>
			</thead>
			<tbody>
				@foreach($mps as $mp)
				<tr>
					<td>{{ $mp->mp }}</td>
					<td>{{ $mp->obra_institucion }}</td>
					<td>{{ $mp->mecanico }}</td>
					<td>{{ $mp->nro_reporte }}</td>
					<td>{{ $mp->fecha_ejecución }}</td>
					<td>{{ $mp->horometro_aprox }}</td>
					<td>{{ $mp->fecha_aprox }}</td>
					<td>
						<label class="form-check-label">
							@if( !isset($mp->realizado) )
							<input class="form-check-input"  type="checkbox" value="1" disabled>
							@else
							<input class="form-check-input"  checked="checked" type="checkbox" value="1" disabled>
							@endif
						</div>
					</td>
					<td>
						<label class="form-check-label">
							@if( !isset($mp->pase) )
							<input class="form-check-input"  type="checkbox" value="1" disabled>
							@else
							<input class="form-check-input"  checked="checked" type="checkbox" value="1" disabled>
							@endif
						</div>
					</td>
					<td>
						<a href="{{ route('maquinarias.mpreventivos.edit' , ['maquinaria' => $mp->maquinaria_id ,
						'mpreventivo' => $mp->mpreventivo_id]) }}" class="btn btn-success  {{ ($mp->status) ? 'disabled' : ''}}" role="button"><i class="fa fa-pencil"></i></a>
					</td>
					<td>
						@if(!$mp->status)
							{!! Form::open([
							'method' => 'DELETE',
							'url' => '/maquinarias/' . $maquinaria->maquinaria_id . '/mpreventivos/' . $mp->mpreventivo_id ]) !!}
							{!! Form::button('<i class="fa fa-trash"></i>',  ['class' => 'btn btn-danger' , 'type' => 'submit']) !!}
							{!! Form::close() !!}
						@else
						<a href="" class="btn btn-danger disabled" role="button"><i class="fa fa-trash"></i></a>
						@endif
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>