sigma_final/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Redirect::to('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/maquinarias/list', 'MaquinariasController@data');

Route::resource('maquinarias', 'MaquinariasController');
Route::resource('maquinarias.mpreventivos', 'MpreventivosController' );

Route::get('/ubicacion/provincia/{id}', 'UbicacionController@maquinarias');
Route::get('/ubicacion/maquinaria/{serie}', 'UbicacionController@buscarMaquinaria');

Route::get('/ubicacion/search/{term}', 'UbicacionController@search');

Route::resource('ubicacion', 'UbicacionController');

Route::resource('admin','AdminController');


Route::resource('maquinarias.mcorrectivos', 'McorrectivosController' );

Route::resource('maquinarias.receta', 'RecetasController' );

Route::resource('maquinarias.movimientos', 'MovimientosController' );

Route::get('/maquinarias/{idMaquinaria}/receta/{idReceta}/detalle/create', 'DetalleRecetaController@create');
Route::post('/detalle', 'DetalleRecetaController@store');
Route::delete('/detalle', 'DetalleRecetaController@destroy');

Route::resource('obras','ObrasController');

Route::resource('proveedores','ProveedoresController');

Route::get('/obras/search/{term}', 'ObrasController@search');
Route::post('/obras/save', 'ObrasController@save');

Route::get('/proveedores/search/{term}', 'ProveedoresController@search');
Route::post('/proveedores/save', 'ProveedoresController@save');

Route::resource('ordencompra','OrdenCompraController');

Route::resource('consumiblesAlmacen','ConsumiblesAlmacenController');

Route::get('/consumiblesAlmacen/search/{term}', 'ConsumiblesAlmacenController@search');
Route::post('/consumiblesAlmacen/save', 'ConsumiblesAlmacenController@save');

Route::resource('consumibles', 'ConsumiblesAlmacenController');

Route::resource('pecosas','PecosasController');	

Route::get('/ordencompra/search/{term}', 'OrdenCompraController@search');

Route::get('/detalles_oc/search/{term}', 'OrdenCompraController@search_detalle_oc');

Route::post('/ordencompra/update/{id}','OrdenCompraController@update');

Route::resource('stockalmacen','StockAlmacenController');

Route::resource('valeconsumo','ValeConsumoController');
Route::post('/valeconsumo/update/{id}','ValeConsumoController@update');

sigma_final/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'SIGMA') }}</title>
        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <!-- Scripts -->
        @yield('style')
        <script>
        window.Laravel = {!! json_encode([
        'csrfToken' => csrf_token(),
        ]) !!};
        </script>
    </head>
    <body>
        <div id="app">
            @if (!Auth::guest())
            <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/ubicacion') }}">SIGMA</a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        @if (!Auth::guest())
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('ubicacion.index') }}">Ubicación</a>
                        </li>
                        @if(Auth::user()->tipo == 1 || Auth::user()->tipo == 3)
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('maquinarias.index') }}">Maquinarias</a>
                        </li>
                        @endif
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('stockalmacen.index') }}">Stock de Almacen</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('ordencompra.index') }}">Orden de Compras</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('pecosas.index') }}">Pecosas</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('valeconsumo.index') }}">Vales de Consumo</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('obras.index') }}">Obras</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('proveedores.index') }}">Proveedores</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ route('consumibles.index') }}">Consumibles</a>
                        </li>
                        @endif
                    </ul>
                    <ul class="navbar-nav my-2 my-lg-0">
                        @if (Auth::guest())
                        <li class="nav-item"><a class="nav-link" href="{{ route('login') }}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ route('register') }}">Register</a></li>
                        @else
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ Auth::user()->name }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{{ route('admin.index') }}">
                                    Admin
                                </a>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    Logout
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </li>
                        @endif
                    </ul>
                </div>
            </nav>
            @endif
            @yield('content')
        </div>
        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}"></script>
        <script src="{{ asset('js/ubicacion.js') }}"></script>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBGmfkx8itWNZGISgI9zdrH-9M8NGrTjQg&callback=initMap">
        </script>
        @yield('script')
    </body>
</html>